version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kompo
      POSTGRES_USER: kompo
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: